---
- name: Creates a new user named admin with sudo privileges
  hosts: test
  gather_facts: false

  tasks:
    - name: Create user
      shell: useradd admin
      become: yes

    - name: Give user a new password 
      user:
        name: admin
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"
      become: yes